version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alaya
  - alint
  - antfu
  - apalis
  - apeira
  - Balatro
  - bbox
  - bufbuild
  - bumpp
  - clippy
  - conv
  - cust
  - decimalturn
  - direnv
  - dotenv
  - fsrs
  - graphiti
  - guiiai
  - haru
  - hnsw
  - iden
  - insel
  - kwaa
  - locomo
  - Logg
  - mediaremote
  - moeru
  - msvc
  - nemori
  - netease
  - nixpkgs
  - ollama
  - oper
  - paradedb
  - pgvector
  - picospinner
  - pkgs
  - pkill
  - plast
  - plastmem
  - pname
  - prefs
  - qwen
  - retrievability
  - rustc
  - rustls
  - schemars
  - seaql
  - serde
  - sonarjs
  - sqlx
  - tinyexec
  - tutils
  - ultralytics
  - utoipa
  - uuidv
  - vchord
  - vite
  - vitejs
  - vitest
  - waifu
  - xiaowu
  - xsai
ignoreWords: []
import: []
